[build]
builder = "nixpacks"
buildCommand = "npm install --prefix backend && npm install --prefix frontend && npx --prefix frontend react-scripts build"

[deploy]
startCommand = "node backend/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10