[build]
builder = "nixpacks"
buildCommand = "npm install --prefix backend && cd frontend && npm install && ./node_modules/.bin/react-scripts build && cd .."

[deploy]
startCommand = "node backend/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10